name: CI
on: [push, pull_request]

jobs:
  unit_tests:
    name: Unit Tests (${{matrix.elixir-otp.elixir}}/${{matrix.elixir-otp.otp}})
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.elixir-otp.experimental || false }}

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    strategy:
      matrix:
        elixir-otp:
          - {otp: 28.x, elixir: 1.19.x}
          - {otp: 28.4.1, elixir: 1.20.0-rc.4, version_type: strict, experimental: true}
      fail-fast: false

    steps:
    - uses: actions/checkout@v6
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{matrix.elixir-otp.otp}}
        elixir-version: ${{matrix.elixir-otp.elixir}}
        version-type: ${{matrix.elixir-otp.version_type || 'loose'}}

    - uses: actions/cache@v5
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}

    - run: mix deps.get
    - run: mix test

  live_view_tests:
    name: LiveView Driver
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    steps:
    - uses: actions/checkout@v6
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 28.x
        elixir-version: 1.19.x

    - uses: actions/cache@v5
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}

    - run: mix deps.get
    - run: mix test.live_view

  chrome_cdp_tests:
    name: Chrome CDP
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    steps:
    - uses: actions/checkout@v6
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 28.x
        elixir-version: 1.19.x
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: actions/cache@v5
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}

    - uses: actions/cache@v5
      with:
        path: .browsers
        key: ${{ runner.os }}-browsers-stable

    - run: mix deps.get
    - run: mix wallabidi.install
    - run: mix test.chrome

  chrome_bidi_tests:
    name: Chrome BiDi
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    steps:
    - uses: actions/checkout@v6
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 28.x
        elixir-version: 1.19.x
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - uses: actions/cache@v5
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}

    - uses: actions/cache@v5
      with:
        path: .browsers
        key: ${{ runner.os }}-browsers-stable

    - run: mix deps.get
    - run: mix wallabidi.install
    - run: mix test.chrome.bidi

  linting:
    name: Linting
    runs-on: ubuntu-latest

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork == true)

    steps:
    - uses: actions/checkout@v6
    - uses: erlef/setup-beam@v1
      with:
        otp-version: 28.x
        elixir-version: 1.19.x

    - uses: actions/cache@v5
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock') }}

    - uses: actions/cache@v5
      with:
        path: _build
        key: ${{ runner.os }}-dialyzer-28-1.19-${{ hashFiles('mix.lock') }}

    - run: mix deps.get
    - run: mix compile --force --warnings-as-errors --no-deps-check
    - run: mix format --check-formatted
    - run: mix credo --strict
    - run: mix dialyzer
